services:
  analysis:
    image: docker.io/derek2403/ai-data-analysis:latest
    ports:
      - "3040:3040"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=3040
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
    volumes:
      - /storage/data:/app/data
      - /storage/results:/app/results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 